### ISSUE TITLE
Develop a 404 Page

### ISSUE THREAD

**Issue by harshithtunuguntla** [harshithtunuguntla/project-osus#1]
**Title:** [Task] Develop a 404 Page for Non Existing Links

**Description:**
Currently if there's a keyword for which a Long URL doesn't exist, we simply throw a browser message LINK NOT FOUND, instead, we can develop a small 404 page additionally prompting users to generate a link using that keyword.

**Comment by Harshavardhan710** [comment]
@harshithtunuguntla am working on it

**Comment by snehachandra1108** [comment]
Hey, can you please assign me this issue, I wanna work on this.

**Comment by harshithtunuguntla** [comment]
@snehachandra1108 , Harsha has already raised a PR for this but it was still incomplete. Do you want to enhance that?

**Comment by snehachandra1108** [comment]
Yes, I am working on it

**Comment by pasamyagnesh** [comment]
> @snehachandra1108 , Harsha has already raised a PR for this but it was still incomplete. Do you want to enhance that?

I fixed the bugs, once check the latest PR.

**Comment by DCGUY009** [comment]
This has been developed and is available to view in the website!
