### ISSUE TITLE
Keyword Validation for URL Shortening

### ISSUE THREAD

**Issue by harshithtunuguntla** [harshithtunuguntla/project-osus#10]
## **Description**

Currently, the website accepts any input (including random characters or spaces) as a valid URL and generates a shortened URL. However, when trying to access the shortened URL, it results in a "link not found" error. The system should not accept invalid URLs or random inputs and should provide proper validation to prevent such behavior.

---

## **Steps to Reproduce**
1. Go to the URL shortening page.
2. Enter random characters or spaces in the input field (e.g., `abcd$123` or `    ` or  `random value`).
3. Click on the 'Shorten' button.
4. Observe that a shortened URL is generated.
5. Try to access the generated shortened URL.
6. See error: "link not found."

---

## **Expected Behavior**

The service should validate the input to ensure that only valid URLs are accepted. If the input is invalid (e.g., random characters or spaces), an error message should be displayed, and the shortened URL should not be generated.

---

## **Actual Behavior**

The system accepts any input, generates a shortened URL, but when trying to access the shortened URL, a "link not found" error is shown.

---

## **Screenshots**

Shortened the URL with a keyword including space
<img width="661" alt="image" src="https://github.com/user-attachments/assets/37717793-c9e4-4bf8-8f75-2d715b28dc81">

However when trying to access it, it's not able to redirect to the link
<img width="886" alt="image" src="https://github.com/user-attachments/assets/73d30c2e-a217-4c6d-99fd-a49e6dccb05f">

---

## **Environment**
- **OS:** [e.g., Windows, macOS, Linux]
- **Version:** [e.g., 1.0.0]
- **Browser:** [e.g., Chrome, Firefox, etc.]

---

## **Additional Context**

The issue occurs due to the lack of validation in the URL input field. Adding proper URL validation would prevent users from submitting invalid URLs or random text, improving the user experience.

**Comment by khangklj** [comment]
Hi @harshithtunuguntla,
Can you assign me this issue?

**Comment by DCGUY009** [comment]
Hi @khangklj you can go ahead and work on this issue. Please remember to fetch the latest code from the repository before you start working!

**Comment by DCGUY009** [comment]
Changes are live on the website, closing this issue!
