### ISSUE TITLE
Duplicate Keyword Error Message Shown As HyperLink

### ISSUE THREAD

**Issue by harshithtunuguntla** [harshithtunuguntla/project-osus#11]
## **Description**

When a user attempts to shorten a URL using a keyword that has already been taken, the system redirects the user and displays the message "The Keyword Already Exists, Choose a Different One" as a hyperlink (`href`). This redirection causes confusion and disrupts the user experience, as the error message should be shown on the same page, allowing users to correct their input without leaving the page.

<img width="735" alt="image" src="https://github.com/user-attachments/assets/ae9ddf95-df06-4113-9cb4-fec43dbc7083">

---

## **Steps to Reproduce**
1. Go to the URL shortening page.
2. Enter a keyword that has already been used for another URL.
3. Click on the "Shorten" button.
4. The user is redirected, and the error message "The Keyword Already Exists, Choose a Different One" is shown as a hyperlink.

---

## **Expected Behavior**

If a user enters a keyword that has already been taken:
- The user should **not** be redirected to another page with that error message.
- An error message (e.g., "The Keyword Already Exists, Choose a Different One") should appear in the form of an **in-place popup**, modal, or alert on the same page.
- The user should be able to correct the keyword immediately and try again without leaving the current page.

---

## **Actual Behavior**

- The user is being shown a **hyperlink** which says "The Keyword Already Exists, Choose a Different One" (`href`).
- This breaks the flow of the shortening process.

---

## **Environment**
- **OS:** [e.g., Windows, macOS, Linux]
- **Version:** [e.g., 1.0.0]
- **Browser:** [e.g., Chrome, Firefox, etc.]

---

## **Additional Context**

The issue impacts user experience, as redirection causes unnecessary page loads. Adding validation to show the error message as a popup or inline message would allow users to immediately correct the input without page redirection.

**Comment by devesh711** [comment]
hey @harshithtunuguntla can you review it. Thanks
