### ISSUE TITLE
Postman API Documentation

### ISSUE THREAD

**Issue by harshithtunuguntla** [harshithtunuguntla/project-osus#14]
## **Current Documentation**

Currently, there is no Postman documentation available for the URL shortening service. Developers do not have a straightforward way to test or integrate the API endpoints using tools like Postman. The lack of a Postman collection makes it difficult for developers to interact with the service for testing, debugging, and understanding the available endpoints.

---

## **Suggested Changes**

1. **Create a Postman Collection:**
   - Develop a Postman collection that includes all available API endpoints for the URL shortening service (e.g., URL shortening, URL redirection, URL expiry, etc.).
   - The collection should include details for each request, such as request type (GET, POST), parameters (e.g., URL, keyword, expiry), and expected responses.

2. **Link Postman Collection in Documentation:**
   - Add a section to the API documentation page on the website that links directly to the Postman collection. 
   - Provide instructions on how to import the collection into Postman, as well as how to use the requests for testing and integration.

3. **Include Example Requests & Responses:**
   - Include example API requests and sample responses for each endpoint to help developers better understand how the service works.

---

## **Additional Resources**

- [Postman Documentation on Creating Collections](https://learning.postman.com/docs/getting-started/creating-the-first-collection/)
- [Postman API Network](https://www.postman.com/explore)

These resources can help in building the Postman collection and improving the documentation experience for developers.

**Comment by pasamyagnesh** [comment]
Hello @harshithtunuguntla ,
/assign

**Comment by DCGUY009** [comment]
Hi @pasamyagnesh you can go ahead and work on this.

Please do mention me whenever you want an issue assigned or commenting in future to get replies faster!

**Comment by DCGUY009** [comment]
Hi @pasamyagnesh are you working on this?

**Comment by pasamyagnesh** [comment]
> Hi @pasamyagnesh are you working on this?

Hey @DCGUY009, I'm working on it. Completed Postman collection. Working on the API docs route.

**Comment by DCGUY009** [comment]
Alright @pasamyagnesh thanks for confirming!

**Comment by harshithtunuguntla** [comment]
Hey @pasamyagnesh , any update on the same?

**Comment by pasamyagnesh** [comment]
> Hey @pasamyagnesh , any update on the same?

Already committed, once check the PR @harshithtunuguntla.

**Comment by DCGUY009** [comment]
Changes are live on the website, thanks @pasamyagnesh working on this 🚀
