### ISSUE TITLE
Enhanced input forms and responsive design implementation.

### ISSUE THREAD

**Issue by Shr3y4sm** [harshithtunuguntla/project-osus#16]
### **Enhanced input**
Autocomplete suggestions for URLs or popular custom keywords suggestion and implementing error handling with clear messaging for **invalid** URLs, confirm that error messages are clear and informative for the user. Still gives a "shortened version" of an invalid URL.

### **Responsive design** 
Ensuring it's fully optimized for mobile users. For mobile version (smaller resolutions) of the website, the buttons are misplaced and not aligned, the logo "OSUS" is also not aligned properly (Refer the screenshot attached, works fine when switched to **"desktop mode"**).

Dark/Light Mode Toggle: Implement a toggle for dark and light mode to improve accessibility and user comfort.

 
 
![WhatsApp Image 2024-10-10 at 22 32 51](https://github.com/user-attachments/assets/c01fdd07-d291-4d45-ab06-a645dd41baa1)

**Comment by DCGUY009** [comment]
Hi @Shr3y4sm I am closing this issue as the website has evolved and also only responsiveness is pending for which another issue is open. Thanks for your suggestions for improving the website!
