### ISSUE TITLE
[ENHANCEMENT] Implement Auto-Focus on URL Input Field for Improved User Experience

### ISSUE THREAD

**Issue by Deepak-Perla** [harshithtunuguntla/project-osus#26]
## Description
On page load, the input field should automatically be selected, allowing users to start typing immediately without needing to click the field manually. This enhancement streamlines the experience for users who are looking for quick URL shortening.

## Proposed Enhancement
Add JavaScript or HTML attributes to ensure the input field gets focus as soon as the page loads.

## Benefits
- Improves user efficiency by reducing unnecessary steps.
- Creates a smoother, faster interaction.
- Makes the UI more intuitive and user-friendly.

## Additional Context
![image](https://github.com/user-attachments/assets/dab571ae-1e7b-4776-b275-21d80b306e98)

**Comment by RupeshRoyal** [comment]
Hi @Deepak-Perla, Please assign it to me.

**Comment by harshithtunuguntla** [comment]
This has been closed!
