### ISSUE TITLE
[ENHANCEMENT] SEO and User Interface Enhancements

### ISSUE THREAD

**Issue by Vyshnavi1322** [harshithtunuguntla/project-osus#29]
once check on this one

**Comment by DCGUY009** [comment]
Hi @Vyshnavi1322 can you please follow the template provided for this issue (Enhancement template) so that whatever you are trying to convey becomes clear to contributors. 

The templates are already pre-configured when you want to create a new issue

**Comment by DCGUY009** [comment]
Hi @Vyshnavi1322 we are closing this issue as we didn't get any reply from you
