### ISSUE TITLE
[BUG] Shortened URL Overflows Container Box for Long Custom Keywords

### ISSUE THREAD

**Issue by DCGUY009** [harshithtunuguntla/project-osus#36]
## Description
The shortened URL text overflows outside the container box when a custom keyword or link exceeds 2 sentences. Although URLs are meant to be concise, this issue affects the user interface (UI) presentation and needs to be addressed.

## Steps to Reproduce
1. Go to the [OSUS URL shortening page](https://project-osus.vercel.app/).
2. Enter any URL (e.g., https://www.google.com).
3. Input a custom keyword that is excessively long (e.g., 3 or more sentences).
4. Click "Shorten" and observe the shortened URL displayed.

## Expected Behavior
The shortened URL should remain contained within the designated box, regardless of the length of the custom keyword or URL, or it should be truncated or wrapped.

## Actual Behavior
The shortened URL spills out of the container box, breaking the layout and affecting the UI's aesthetics.

## Screenshots
![image](https://github.com/user-attachments/assets/fe4101ef-e5ee-4f67-8e20-621fc53addda)

## Environment
- OS: Windows
- Version: 11
- Browser: Brave

## Additional Context
Though the URL's length should not typically exceed 2 sentences, from a UI perspective, proper text wrapping, truncation, or scroll bars should be implemented to prevent layout breaks.

**Comment by DCGUY009** [comment]
Hi @BimleshRB assigned it to you, happy hacking!

**Comment by harshithtunuguntla** [comment]
This has been resolved!!
