### ISSUE TITLE
 Analytics End Point Development

### ISSUE THREAD

**Issue by harshithtunuguntla** [harshithtunuguntla/project-osus#4]
## Description
As of now analytics end point is not developed, we need to develop that end point to show the clicks count for a specific URL

## Benefits
This'll help the user to track the link clicks for their URL

## Additional Context
We can either develop the end point directly or think of a different solution where in user can add query params like ?know=linkclicks so that for the same url we will give the link clicks

**Comment by pasamyagnesh** [comment]
Hey @harshithtunuguntla,
I will be working on the '/analytics' endpoint.

**Comment by harshithtunuguntla** [comment]
Sure @pasamyagnesh ! This has been assigned to you. Do make sure you've registered for hacktoberfest before raising a PR to make every contribution count.

**Comment by DCGUY009** [comment]
This issue has been closed and the changes are reflected on the website!
