### ISSUE TITLE
[UI/UX] Header Button hover effect text is not visible

### ISSUE THREAD

**Issue by Shashi1024** [harshithtunuguntla/project-osus#46]
## Description
The text on header buttons is not visible due to hover effect [ text colour same as background colour ]

## Proposed Changes
Text colour and the background colour must be different in the hover effect

## Examples
Before:
<img width="1048" alt="Screenshot 2024-10-13 at 4 27 05 PM" src="https://github.com/user-attachments/assets/efe5011c-ada8-4a50-91a5-95479269d83f">

After:
<img width="886" alt="Screenshot 2024-10-13 at 4 43 58 PM" src="https://github.com/user-attachments/assets/39c21de0-729d-45b8-b3e7-1d9fd61a4fea">

Can you please assign me this issue under hacktoberfest

**Comment by Deepak-Perla** [comment]
Hey @Shashi1024, would you like to do it. We will assign it to you. 😊

**Comment by Shashi1024** [comment]
I would like to do it, Please assign it to me under hacktoberfest

**Comment by DCGUY009** [comment]
Hi @Shashi1024 and @nitish-002,
We failed to notice that Shashi had included "Assign me this Issue" when raising it, which led to us asking him again whether to assign this issue or not causing confusion and unintended duplication of effort. We apologise for the oversight regarding this issue.

To clarify:
1. We will be accepting @Shashi1024's PR as he initially requested assignment.
2. @nitish-002, we kindly ask you to choose another issue to work on.

Moving forward, please remember to wait for assignment by us before working on any issues. This will help prevent similar conflicts in the future.

Thank you for your understanding and continued contributions.

**Comment by DCGUY009** [comment]
This has been closed and the changes are reflected on the website!
