### ISSUE TITLE
Make Page Fully Responsive

### ISSUE THREAD

**Issue by Sumit1911** [harshithtunuguntla/project-osus#51]
## Description
The page isn't fully responsive, causing layout issues on smaller screens, such as misaligned text and oversized images, affecting user experience.

## Proposed Changes
Use media queries to adjust layout for different screen sizes (mobile, tablet, desktop).
Update CSS for better scaling of images, text, and buttons.
Ensure elements adjust and align properly on smaller screens.

![image](https://github.com/user-attachments/assets/93ce52ec-76a5-4393-af7e-f7e2496c5da1)

**Comment by DCGUY009** [comment]
Hi @Sumit1911 do you want to work on this issue?

**Comment by Sumit1911** [comment]
Yes, please assign this issue with hactoberfest label

**Comment by DCGUY009** [comment]
Hi @Sumit1911 it's assigned to you! Don't forget to pull the latest code from the repository and register for hacktober fest in their official website before raising a PR.
Happy Hacking 🚀

**Comment by Roshanchenna** [comment]
Can I work on this, is the issue still available to work on ?? If so please assign it to me. I want to work

**Comment by DCGUY009** [comment]
Hey @Roshanchenna, @Sumit1911 is already working on this. You can choose an issue from the Issue tab or create a new issue if you have any improvements you think you can make!

**Comment by DCGUY009** [comment]
Hi @Sumit1911 are you still working on this issue? If you are not please do mention so that @Roshanchenna can take this up!

**Comment by DCGUY009** [comment]
To be clear on the improvements for this issue, if someone wants to take this up:
1. For smaller screens remove the "OSUS"    text in the logo and only display the dashed O to make it look good (or) you can do the reverse if it makes more sense 
2. For the buttons on the right (Know More, Analytics, Documentation) put them in a hamburger menu and as menu items rather than buttons, because that would make more sense!

**Comment by Sumit1911** [comment]
I am working on it.

**Comment by DCGUY009** [comment]
Alright @Sumit1911 work on this and please do tag me when commenting so that I can get to know the updates faster!

**Comment by DCGUY009** [comment]
Please do fetch the latest code before working on this @Sumit1911

**Comment by DCGUY009** [comment]
Changes are live on the website!
