### ISSUE TITLE
[DOC] Title: Add Code of conduct

### ISSUE THREAD

**Issue by Annapoornaaradhya** [harshithtunuguntla/project-osus#55]
## Current Documentation
Code of conduct file is not included

## Suggested Changes
Want to add code of conduct.md

**Comment by Roshanchenna** [comment]
please assign me this task

**Comment by DCGUY009** [comment]
Hi @Roshanchenna, @Annapoornaaradhya raised this request. Seems like she is willing to work on this, but it's not clear.

@Annapoornaaradhya do you want me to assign this issue?

**Comment by Annapoornaaradhya** [comment]
@DCGUY009 yes please assign me this issue.
I'm sorry I missed this line while rising the issue

**Comment by DCGUY009** [comment]
Alright @Annapoornaaradhya you can go ahead and work on this issue. Happy hacking 🚀

@Roshanchenna kindly choose another issue or raise an issue if you feel there are any improvements to be made!
