### ISSUE TITLE
[BUG] Buttons are not consistent with Home Page in Analytics page

### ISSUE THREAD

**Issue by DCGUY009** [harshithtunuguntla/project-osus#59]
## Description
Buttons design is not consistent with the home page. 

## Steps to Reproduce
1. Go to the home page
2. Click on Analytics button in the header 
3. On the Analytics page you can see that buttons colors and designs are not consistent with the home page

## Expected Behavior
When the user hovers on the buttons or clicks on it, in all the pages the behaviour has to be consistent

## Actual Behavior
Right now in the analytics page buttons when hovered the text dissapears

## Screenshots
![image](https://github.com/user-attachments/assets/67ea97b2-9c90-4502-8a0f-be70cacab1fe)
![image](https://github.com/user-attachments/assets/204272e6-ae6e-4d42-b9ae-f0931f11c268)

## Environment
- OS: Windows
- Version: 11
- Browser: Brave

**Comment by AmanWebDev2** [comment]
@DCGUY009 can you assign this bug to me?

**Comment by DCGUY009** [comment]
Hi @AmanWebDev2 you can go ahead and work on this issue. happy Hacking 🚀

**Comment by DCGUY009** [comment]
Changes are live on the website!
