### ISSUE TITLE
Add Copy-to-Clipboard Button for Generated Short URLs

### ISSUE THREAD

**Issue by saranya-ayyapu** [harshithtunuguntla/project-osus#6]
## Description
I would like to request the addition of a "copy-to-clipboard" button for the generated short URLs on Project OSUS. This feature would allow users to easily copy the shortened URL with one click, improving the user experience.

## Motivation
Currently, users have to manually select and copy the short URL. By adding this button, we simplify the process, making it faster and more intuitive. This is especially helpful for users who frequently share URLs.

## Proposed Solution
1. Add a "copy" button next to the generated short URL.
2. When clicked on copy button, it'll copy the URL to the user's clipboard.
3. Provide feedback (like an alert or text change on the screen) to inform the user that the URL has been successfully copied.

## Additional Context
This is a common feature in URL shorteners like Bit.ly and TinyURL. It can be implemented using JavaScript with the document.execCommand('copy') method for compatibility across browsers.

**Comment by harshithtunuguntla** [comment]
Sure, that is great!! I'm assigning the same to you, you can work on it and raise a PR! 

Also: Make sure you've registered for hacktoberfest to make this PR count :)

**Comment by saranya104** [comment]
Thanks Harshith! I've Registered now for hacktoberfest and i'll work on it and raise PR accordingly.

**Comment by saranya104** [comment]
I've made a pr with a file which has changes into the main codebase.
But I wanted to clarify, should I:
Create a new file for the copy button enhancement and upload it?
Or, should I directly upload the modified code changes into the main codebase?

**Comment by harshithtunuguntla** [comment]
Hey @saranya104 good question!

I hope you've forked the repo, cloned it to your local.

Now once you've cloned it into local, create a new branch using git checkout -b clipboard-changes.

Once you've done that you'll see exact same files there. Now do whatever changes you want to do there, then commit and push them to git.

Once you've done that come back to this repo where you'll see pull request button which you can raise.

to make it simple, you'll directly make changes in main code base, no separate files are required.

**Comment by saranya104** [comment]
Thanks @harshithtunuguntla now i've understood easily, made changes into my branch and pulled a pr, review and update!

**Comment by DCGUY009** [comment]
Changes are reflected on the main [website](https://project-osus.vercel.app/)
