### ISSUE TITLE
[ENHANCEMENT] Documentation Page Consistency

### ISSUE THREAD

**Issue by DCGUY009** [harshithtunuguntla/project-osus#61]
## Description
There is a documentation page in the website but it is not consistent with the theme of the website. We don't have to change the whole page but at least look into making it more consistent with the main theme of the website!

## Benefits
This will make it more seamless for the users while interacting

## Improvements
1. We can change the header to make it look more like the home page and analytics page
2. Navigation to other pages from the documentation page is not present, we can add that 
3. The page icon for the browser tab is missing for the documentation page, the name in the documentation page could be "URL Shortener | Documentation" instead of "Project OSUS - Open Source URL Shortener"
![image](https://github.com/user-attachments/assets/c519c440-5db6-45c4-a1f3-9d61ebc2ca71)
![image](https://github.com/user-attachments/assets/d8f077cf-463f-4113-ba72-18948c2a8717)
4. A similar name change in Analytics page can also be made from "Analytics" to "URL Shortener | Analytics" to make the design consistent
![image](https://github.com/user-attachments/assets/2373c9bb-51e3-49dc-9929-31ae8442d346)
5. Overall it looks like a separate page without any connection to the original website, we can work on making it consistent to the original website!

## Additional Context
![image](https://github.com/user-attachments/assets/43d701cb-e9ea-4701-ba85-223f51496cee)
![image](https://github.com/user-attachments/assets/75f28aba-9d37-4505-8fea-13eea08c40cf)

**Comment by imsudiptaa** [comment]
Hello @DCGUY009 can you assign me this with the label of hacktoberfest ? I would like to work on this

**Comment by DCGUY009** [comment]
Hi @imsudiptaa devesh is already working on this. We have a PR running just for this. If he doesn't want to work on it, you can do it.

@devesh711 can sudipta do this PR or are you doing it?

**Comment by devesh711** [comment]
it's just done I will push few changes soon.
