### ISSUE TITLE
[UI/UX] I can make this responsive as well as fix the buttons at the top corner 

### ISSUE THREAD

**Issue by Bhumika-00** [harshithtunuguntla/project-osus#7]
## Description
As we can clearly see from the image that both the buttons are mixing into each other so I will fix that issue by resizing it and making the website responsive as well as a little change in the colour theme is also required.

## Proposed Changes
I will resize the buttons there and change the colour theme to the shades of purple which will make it more attractive and reliable.

## Examples
I have provide an image for the theme.
![Screenshot_2024-10-10-19-26-08-565_com android chrome](https://github.com/user-attachments/assets/c80f43e3-1808-4d42-afa1-90e39c611808)
![Screenshot_2024-10-10-19-22-43-140_com instagram android](https://github.com/user-attachments/assets/c595c108-5717-4198-9dba-535d58212eef)

**Comment by harshithtunuguntla** [comment]
This is awesome @Bhumika-00 ! We'd love to see those changes! Assigning the same to youu!! 

Make sure you've registered for hacktoberfest to make every PR count!!

**Comment by Bhumika-00** [comment]
Great thankyou

**Comment by Bhumika-00** [comment]
Hey I have made the changes please give me the vercel access so that it can
be viewed and accepted as soon as possible

Thanks

**Comment by Bhumika-00** [comment]
VID_20241011_205835(0).mp4
<https://drive.google.com/file/d/1Jp_EtRtChgfB0HWr-0PW1gn0x58dWX0i/view?usp=drivesdk>
This is the proof and the resultant website as stated while raising the
issue.

**Comment by DCGUY009** [comment]
The changes are reflected in the [website](https://project-osus.vercel.app/)
