### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by harshithtunuguntla** [harshithtunuguntla/project-osus#9]
**Title**: Refactor code for better readability

**Description:**
Some parts of the codebase can be difficult to read and understand, especially for beginners. Consider refactoring the following areas to improve clarity!

You can choose to work on any of the tasks below:

- [ ] Refactor large functions into smaller ones.

- [ ] Rename variables and functions to make their purpose clearer.

- [ ] Simplify any complex logic or remove redundancies.

**Comment by adarsh4k** [comment]
hi anna 
i am intrested on this 
can i do it ?
please assign it to me

**Comment by DCGUY009** [comment]
Hi @adarsh4k you can go ahead and work on this! Happy Hacking 🚀

Please do tag me when commenting for getting faster replies!

**Comment by DCGUY009** [comment]
Changes are live on the website!
